export let chatHistory = [
  {
    id: 0,
    name: 'Alibey Ibrahimli',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 1,
    name: 'Ferid Samadov',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 2,
    name: 'CAvid Kerimbeyli',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 3,
    name: 'WoPiker Woody',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 4,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 5,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 6,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 7,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 8,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 9,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 10,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 11,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
  {
    id: 12,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },

  {
    id: 13,
    name: 'Ali Ibra',
    lastChat: 'how you doing?',
    time: 'Jun 11, 2020',
    img: '../../../../assets/download.jpeg',
  },
];
